array_push(songs, new add_song("event:/Music/Soundtest/stormsover", "Wake Me Up Later - Internetty Spaghetti"))
array_push(songs, new add_song("event:/Music/Soundtest/hub1", "Welcome Back - Varies"))
array_push(songs, new add_song("event:/Music/Soundtest/tutorial", "Canned Air and RAM Dreams - Varies"))
array_push(songs, new add_song("event:/Music/Soundtest/wayback", "Through Troubled Waters - Mildrux, Varies"))
array_push(songs, new add_song("event:/Music/Soundtest/shellcity", "Beggars Cant Be Choosers - Internetty Spaghetti"))
array_push(songs, new add_song("event:/Music/Soundtest/fruitcup", "We Are People of The Universe - Mildrux, Varies"))
array_push(songs, new add_song("event:/Music/Soundtest/escape", "Good Mourning! - Internetty Spaghetti, Mildrux"))
array_push(songs, new add_song("event:/Music/Soundtest/lap", "Raise The Roof - Varies"))
array_push(songs, new add_song("event:/Music/Soundtest/miltontheme", "The Mole from Underground - Varies, Mildrux", true))
array_push(songs, new add_song("event:/Music/Soundtest/credits", "Our Vacations End - Mildrux"))
array_push(songs, new add_song("event:/Music/Soundtest/waybacksecret", "We're bound to meet again someday, Wayback - Mildrux"))
array_push(songs, new add_song("event:/Music/Soundtest/shellcitysecret", "Cracked like the shell of my heart - Mildrux"))
array_push(songs, new add_song("event:/Music/Soundtest/fruitcupsecret", "Our love was as sweet as fruitcups - Mildrux"))
array_push(songs, new add_song("event:/Music/Soundtest/coffeebreak", "Coffee Break - Mildrux"))
array_push(songs, new add_song("event:/Music/Soundtest/ascendfromdarkness", "You Must Ascend From Darkness#(Bonus Track) - Mildrux, Varies"))