pal_swap_set(obj_player.sprites.player_pal, obj_player.palette_index, false)
draw_sprite_ext(sprite_index, image_index, x, y, image_xscale, image_yscale, image_angle, image_blend, image_alpha)
shader_reset()
pattern_draw(sprite_index, image_index, x, y, image_xscale, image_yscale, image_angle, image_blend, image_alpha, global.patternSpr, obj_player.sprites.palette_colors, obj_player.sprites.player_pal, obj_player.palette_index)
reset_blendmmode()