if !surface_exists(screenSurface)
	screenSurface = surface_create(SCREEN_WIDTH, SCREEN_HEIGHT)
surface_set_target(screenSurface)
draw_clear_alpha(c_black, 0)
draw_set_color(c_white)
draw_set_font(global.creditsfont)
draw_set_halign(fa_center)
draw_set_color(c_red)
draw_text_oyh(SCREEN_WIDTH / 2 + irandom_range(-1, 1), 64 + irandom_range(-1, 1), "DISCLAIMER!")
draw_set_color(c_white)
draw_text_oyh(SCREEN_WIDTH / 2, 128, "Fidelity Hotel uses screen shaders and#flashing lights thatmay be too much for some players.#Be sure to disable this in options!####[wave]Press [J] to Continue")
surface_reset_target()
draw_surface_ext(screenSurface, 0 + (SCREEN_WIDTH / 2 * (1 - image_xscale)), 0 + (SCREEN_WIDTH / 2 * (1 - image_xscale)), image_xscale, image_yscale, image_angle, image_blend, image_alpha)
surface_free(screenSurface)